AWSTemplateFormatVersion: 2010-09-09

Description: VPC and Subnet create
# ------------------------------------------------------------#
#  VPC
# ------------------------------------------------------------#
# VPC Create

Resources:
  VPC10:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsHostnames: true
      EnableDnsSupport: true
      Tags:
      - Key: Name
        Value: RaiseTech-vpc10

# InternetGateway Create
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: RaiseTech-igw-vpc10  

# IGW Attach
  InternetGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPC10
      InternetGatewayId: !Ref InternetGateway

# ------------------------------------------------------------#
#  Subnet
# ------------------------------------------------------------#
# Subnet Create
# Public Subnet1 Create
  PublicSubnet1vpc10: 
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: ap-northeast-1a
      VpcId: !Ref VPC10
      CidrBlock: 10.0.0.0/20
      Tags:
        - Key: Name
          Value: Raisetech-vpc10-publicsubnet1

# Public Subnet2 Create
  PublicSubnet2vpc10: 
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: ap-northeast-1c
      VpcId: !Ref VPC10
      CidrBlock: 10.0.16.0/20
      Tags: 
        - Key: Name
          Value: Raisetech-vpc10-publicsubnet2

# Private Subnet1 Create
  PrivateSubnet1vpc10: 
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: ap-northeast-1a
      VpcId: !Ref VPC10
      CidrBlock: 10.0.128.0/20
      Tags:
        - Key: Name
          Value: Raisetech-vpc10-privatesubnet1


# Private Subnet2 Create
  PrivateSubnet2vpc10: 
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: ap-northeast-1c
      VpcId: !Ref VPC10
      CidrBlock: 10.0.144.0/20
      Tags:
        - Key: Name
          Value: Raisetech-vpc10-privatesubnet2


# ------------------------------------------------------------#
#  RouteTable
# ------------------------------------------------------------# 
# Public RouteTable Create
  PublicRouteTablevpc10: 
    Type: AWS::EC2::RouteTable
    Properties: 
      VpcId: !Ref VPC10
      Tags: 
        - Key: Name
          Value: vpc10-public-routetable

# Private RouteTable Create
  PrivateRouteTablevpc10: 
    Type: AWS::EC2::RouteTable
    Properties: 
      VpcId: !Ref VPC10
      Tags: 
        - Key: Name
          Value: vpc10-private-routetable

# ------------------------------------------------------------#
# Routing
# ------------------------------------------------------------# 
# PublicRoute Create
  PublicRoutevpc10: 
    Type: AWS::EC2::Route
    Properties: 
      RouteTableId: !Ref PublicRouteTablevpc10
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

# ------------------------------------------------------------#
# RouteTable Associate
# ------------------------------------------------------------# 
# PublicRouteTable Associate Subnet1
  PublicSubnet1RouteTableAssociationvpc10: 
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties: 
      SubnetId: !Ref PublicSubnet1vpc10
      RouteTableId: !Ref PublicRouteTablevpc10

# PublicRouteTable Associate Subnet2
  PublicSubnet2RouteTableAssociationvpc10: 
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties: 
      SubnetId: !Ref PublicSubnet2vpc10
      RouteTableId: !Ref PublicRouteTablevpc10

# PrivateRouteTable Associate Subnet1
  PrivateSubnet1RouteTableAssociationvpc10: 
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties: 
      SubnetId: !Ref PrivateSubnet1vpc10
      RouteTableId: !Ref PrivateRouteTablevpc10

# PrivateRouteTable Associate Subnet2
  PrivateSubnet2RouteTableAssociationvpc10: 
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties: 
      SubnetId: !Ref PrivateSubnet2vpc10
      RouteTableId: !Ref PrivateRouteTablevpc10

# ------------------------------------------------------------#
# Output Parameters
# ------------------------------------------------------------#                
Outputs:
  # VPC
  VPC10:
    Value: !Ref VPC10
    Export:
      Name: VPC10

    # Subnet
  PublicSubnet1vpc10:
    Value: !Ref PublicSubnet1vpc10
    Export:
      Name: PublicSubnet1vpc10

  PublicSubnet2vpc10:
    Value: !Ref PublicSubnet2vpc10
    Export:
      Name: PublicSubnet2vpc10

  PrivateSubnet1vpc10:
    Value: !Ref PrivateSubnet1vpc10
    Export:
      Name: PrivateSubnet1vpc10

  PrivateSubnet2vpc10:
    Value: !Ref PrivateSubnet2vpc10
    Export:
      Name: PrivateSubnet2vpc10
